### ISSUE TITLE
Inquiry About Training with Plenoptic Video Dataset

### ISSUE THREAD

**Issue by SHIBOYA** [JarrentWu1031/SC4D#2]
Hi, I have been exploring the code you shared and am planning to use it for training on the Plenoptic Video Dataset. I have a couple of questions and would greatly appreciate your guidance:

Is this code compatible with the Plenoptic Video Dataset for training? If so, are there any specific modifications or adjustments I need to make in the code or configuration files?

If it is possible to use this dataset, what changes should I make to the training command? For instance, do I need to adjust certain parameters in the configuration file to accommodate this particular dataset?

Thank you very much for your assistance. I look forward to your response.

Best regards!

**Comment by JarrentWu1031** [comment]
Hi Boya! I wonder whether you are aiming at 4D generation or reconstruction? SC4D falls under the former category, and its main distinction from reconstruction is that, in this work's setting, the target object has large areas that are not visible. These invisible regions need to be completed utilizing generative models like Zero123, among others. If you are looking to reconstruct 4D scenes without relying on any prior knowledge, I recommend referring to [SC-GS](https://github.com/yihua7/SC-GS), as it includes many training details to ensure reconstruction quality.

**Comment by SHIBOYA** [comment]
Thank you so much for your prompt. I get the clarification regarding the differences between SC-GS and SC4D.

Thanks again for your support!
