### ISSUE TITLE
GUI for sparse control points editing 

### ISSUE THREAD

**Issue by Friedrich-M** [JarrentWu1031/SC4D#5]
Thank you for your excellent work! I noticed that the GS rendering code references SC-GS. I was wondering if the codebase includes support for interactive editing of sparse control points via a GUI, similar to what SC-GS offers?

**Comment by JarrentWu1031** [comment]
> Thank you for your excellent work! I noticed that the GS rendering code references SC-GS. I was wondering if the codebase includes support for interactive editing of sparse control points via a GUI, similar to what SC-GS offers?

Thanks for your appreciation! Currently we do not support interactive editing in our codebase since we focus on the learning of motion and adaptation of motion onto other entities. I might add the GUI option in the future!

**Comment by Friedrich-M** [comment]
Looking forward for your GUI support! Thanks.
